version: '1.1'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - simpledb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TestDb890

  app:
    build:
      context: app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: TestDb890
    depends_on:
      - db

  proxy:
    build:
      context: nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - app

volumes:
  simpledb:
