version: '1.0'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - simpledb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TestDb&890

  app:
    build:
      context: app
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: TestDb&890
    depends_on:
      - db

volumes:
  simpledb:
